{
 "title": "Database Exporter (PostgreSQL)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Длительность последнего сбора Exporter",
   "type": "stat",
   "description": "Среднее время последнего цикла сбора данных.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(pg_exporter_last_scrape_duration_seconds[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество живых строк",
   "type": "stat",
   "description": "Показывает текущее количество активных (неудалённых) строк в таблице. Удобно для мониторинга объёма данных.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(relname) (pg_stat_user_tables_n_live_tup{relname=\"olist_customers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество запросов к Prometheus handler",
   "type": "barchart",
   "description": "Рост количества успешных запросов за последние 5 минут.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(promhttp_metric_handler_requests_total{code=\"200\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Активное время (сек)",
   "type": "timeseries",
   "description": " Измеряет, сколько времени в среднем за последние 5 минут база данных была активна (выполняла запросы). Помогает определить пиковые нагрузки.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_active_time_seconds_total{datname=\"ShopSight-Analytics\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество сборок мусора",
   "type": "timeseries",
   "description": "Частота выполнения сборщика мусора.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Лимит подключений",
   "type": "stat",
   "description": "Отображает максимальное количество соединений, которое разрешено сервером PostgreSQL. Используется для анализа доступных ресурсов и планирования нагрузки.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_settings_max_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Время последней GC",
   "type": "stat",
   "description": "Время, прошедшее с последней сборки мусора. → использует time()",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time()", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Активные подключения",
   "type": "gauge",
   "description": "Показывает количество текущих активных подключений к базе данных. Чем выше значение, тем больше клиентов одновременно работает с сервером. Помогает отследить перегрузку соединениями.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"ShopSight-Analytics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование памяти экспортера (MB)",
   "type": "timeseries",
   "description": "Отслеживает объём оперативной памяти, используемой самим PostgreSQL Exporter. Если показатель растёт, возможно, есть утечка памяти или перегрузка.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Размер базы данных (MB)",
   "type": "stat",
   "description": "Отображает текущий размер базы данных в мегабайтах. Рост графика со временем показывает увеличение объёма данных.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"ShopSight-Analytics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер индексов таблиц (MB)",
   "type": "barchart",
   "description": "Отображает размер индексов выбранной таблицы. Позволяет понять, сколько места занимают индексы и оптимизирована ли структура данных.\n7 Количество живых строк ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(relname) (pg_stat_user_tables_index_size_bytes{relname=\"olist_customers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование лимита (%)",
   "type": "gauge",
   "description": "Показывает процент использованных подключений относительно максимального лимита. Если значение приближается к 100%, сервер близок к перегрузке.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"ShopSight-Analytics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{\"pg_settings_max_connections * 100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}